package ar.changeo.identity.api;

public enum Capability {
    BROWSE_GENERAL, VIEW_SENSITIVE, VIEW_ADULT, DRAFT_REQUEST, DRAFT_OFFER,
    NEW_REQUEST, NEW_PROVIDER_PARTICIPATION, SEND_MARKETPLACE_MESSAGE,
    ACCEPT_AGREEMENT, SYNTHETIC_FUNDING_ELIGIBILITY, GRANT_IN_PERSON_CONSENT,
    ACCESS_EXISTING_OBLIGATION, ACCESS_SUPPORT, ACCESS_FINANCIAL_RIGHTS,
    ADMIN_IDENTITY, ADMIN_RESTRICTIONS, ADMIN_AUDIT,
    ADMIN_MODERATION_REVIEW, ADMIN_MODERATION_AUDIT
}
