package ar.changeo.moderation.api;

public enum SurfaceKind {
    PROFILE_DISPLAY, PROFILE_BIO, PROFILE_MEDIA, OFFER_TITLE, OFFER_BODY, OFFER_MEDIA,
    REQUEST_TITLE, REQUEST_BODY, REQUEST_MEDIA, PUBLIC_POST, QUESTION, COMMENT,
    COMPLETED_JOB_REVIEW, QUOTE_DESCRIPTION, JOB_FEEDBACK, PRIVATE_MESSAGE, ATTACHMENT
}
